#pragma once


#define PMI_MEMORY_ALLOCATOR_RECORDER_ENABLE_LEVEL		(1)	

#define PMI_STCPARAM_TLV_STEP               (65536)
#define PMI_STCPARAM_4K_BUFFER_NODE_SIZE    (4096)
#define PMI_STCPARAM_4K_BUFFER_NODE_STEP    (1024)
#define PMI_STCPARAM_PATH_DEFAULT_LENGTH    (1)
#define PMS_STCPARAM_PILO_PREDEF_DIR_CNF    "cnf"
#define PMS_STCPARAM_PILO_PREDEF_DIR_TMP    "tmp"
#define PMS_STCPARAM_PILO_PREDEF_DIR_LOG    "log"

