#include "meta_src_node.hpp"
#include <vector>
#include <fstream>

namespace pilo
{
    namespace core
    {
        namespace autogen
        {
            static std::string _s_file_header = 
R"(////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                //
//  .----------------.  .----------------.  .----------------.  .----------------.   Generated By //
//  | .--------------. || .--------------. || .--------------. || .--------------. | PILO autogen //
//  | |   ______     | || |     _____    | || |   _____      | || |     ____     | |  |\.-"-./|   //
//  | |  |_   __ \   | || |    |_   _|   | || |  |_   _|     | || |   .'    `.   | |  \`     `/   //
//  | |    | |__) |  | || |      | |     | || |    | |       | || |  /  .--.  \  | |  |= ^Y^ =|   //
//  | |    |  ___/   | || |      | |     | || |    | |   _   | || |  | |    | |  | |  \__ ^ __/   //
//  | |   _| |_      | || |     _| |_    | || |   _| |__/ |  | || |  \  `- - '/  | |  /`=+o+=`\   //
//  | |  |_____|     | || |    |_____|   | || |  |________|  | || |   `.____.'   | | |         |  //
//  | |              | || |              | || |              | || |              | | | (     ) |  //
//  | '--------------' || '--------------' || '--------------' || '--------------' | (,,)---(,,)  //
//  '----------------'  '----------------'  '----------------'  '----------------'   𝓓𝓪𝓶𝓷𝓮𝓭𝓒𝓪𝓽  //
//                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////)";


            autogen_config g_autogen_config;
            ::pilo::core::algorithm::uint_sequence_generator<unsigned int> meta_src_node::_s_seq_generator = ::pilo::core::algorithm::uint_sequence_generator<unsigned int>();

            meta_src_node::meta_src_node(meta_node_type_enum mnte, ::pilo::i16_t indent, ::pilo::u64_t modifier) 
                : _m_type(mnte), _m_indent(indent), _m_id(_s_seq_generator.next()), _m_modifiers(modifier)
            {
                
            }

            meta_src_node::~meta_src_node()
            {
            }


            std::string load_file_header_signature(const std::string& filepathname)
            {
                if (filepathname.empty()) {
                    return _s_file_header;
                }
                std::ifstream file(filepathname);
                if (!file) {
                    return "// Generated by PILO Autogen";
                }

                std::string content((std::istreambuf_iterator<char>(file)),
                    std::istreambuf_iterator<char>());
                return content;
            }

            void s_gen_lines_cpp(std::stringstream& ss, const std::vector<std::unique_ptr<meta_src_node>>& lines, ::pilo::i16_t indent, ::pilo::u32_t flags)
            {
                for (auto it = lines.cbegin(); it != lines.cend(); it++) {
                    (*it)->set_indent(indent);
                    (*it)->append_to_stringstream_cpp(ss, flags, "");
                }
            }

        }
    }
}
